#!/usr/bin/env python

import sys
import json
import os.path

dotconf = os.path.expanduser("~/.chathamrc")
dot = json.load(open(dotconf, 'r'))
obj = json.load(open(sys.argv[1], 'r'))

print "%s %s%s" % (
    "dget",
    dot['master_root'],
    obj['dsc']
)
