#!/usr/bin/env python

import sys
import json
import os.path

dotconf = os.path.expanduser("~/.chathamrc")

dot = json.load(open(dotconf, 'r'))
obj = json.load(open(sys.argv[1], 'r'))

dists = dot['dists']
requirements = obj['requirements']

dist = [ x for x in requirements if x in dists ]

if len(dist) > 1:
    print "Oh shit."
    sys.exit(1)

dist = dist[0]
print dist
