#!/usr/bin/env python

import sys
import json
import os.path

dotconf = os.path.expanduser("~/.chathamrc")

dot = json.load(open(dotconf, 'r'))
obj = json.load(open(sys.argv[1], 'r'))

cplrs = dot['compilers']
requirements = obj['requirements']

cplr = [ x for x in requirements if x in cplrs ]

if len(cplr) > 1:
    print "Oh shit."
    sys.exit(1)

cplr = cplr[0]
print cplr
