#!/bin/bash

abspath() {
    echo `cd \`dirname $1\`; pwd`/`basename $1`;
}

if [ "x$1" == "x" ]; then
    echo "Need a build dump"
    exit 1
fi

FILE=$(abspath $1)

DIST=$(chatham-dist $FILE)
CPLR=$(chatham-compiler $FILE)
TRIPPLE="$DIST-chatham-$CPLR"

TMPDIR=$(mktemp -d)
cd $TMPDIR

echo ""
echo " ===="
echo ""
echo " Tripple: $TRIPPLE"
echo ""
echo " ===="
echo ""

$(chatham-dget $FILE)
sbuild -A -c $TRIPPLE -d $DIST *dsc
BUILD_OK=$?

chatham-postbuild $FILE $BUILD_OK

cd - > /dev/null
rm -rf $TMPDIR
