#!/usr/bin/env python

import sys
import json
import os.path

dotconf = os.path.expanduser("~/.chathamrc")

dot = json.load(open(dotconf, 'r'))
obj = json.load(open(sys.argv[1], 'r'))

if "err" in obj:
    print "Bleh. Error: %s" % (obj['err'])
    sys.exit(1)
